apiVersion: slate.io/v1
kind: Server
metadata:
  name: main-db
  namespace: acme
spec:
  store: memory
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
---
apiVersion: slate.io/v1
kind: Collection
metadata:
  name: accounts
  namespace: acme
spec:
  server: main-db
  indexes:
    - status
    - score
---
apiVersion: slate.io/v1
kind: Collection
metadata:
  name: prospects
  namespace: acme
spec:
  server: main-db
  indexes:
    - stage
---
apiVersion: slate.io/v1
kind: ListView
metadata:
  name: active-accounts
  namespace: acme
spec:
  collectionRef: accounts
  title: Active Accounts
  columns:
    - header: Name
      field: name
      dataType: string
      width: 200
      pinned: true
    - header: Status
      field: status
      dataType: string
      width: 100
      pinned: false
    - header: Score
      field: score
      dataType: int
      width: 80
      pinned: false
