apiVersion: slate.io/v1
kind: Server
metadata:
  name: main-db
  namespace: acme
spec:
  store: memory
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
---
apiVersion: slate.io/v1
kind: Collection
metadata:
  name: accounts
  namespace: acme
spec:
  server: main-db
  indexes:
    - status
    - score
---
apiVersion: slate.io/v1
kind: Collection
metadata:
  name: prospects
  namespace: acme
spec:
  server: main-db
  indexes:
    - stage
---
apiVersion: slate.io/v1
kind: ListView
metadata:
  name: active-accounts
  namespace: acme
spec:
  collectionRef: accounts
  title: Active Accounts
  columns:
    - header: Name
      field: name
      dataType: string
      width: 200
      pinned: true
    - header: Status
      field: status
      dataType: string
      width: 100
      pinned: false
    - header: Score
      field: score
      dataType: int
      width: 80
      pinned: false
---
# ── Lists Service ────────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: active-accounts-list
  namespace: acme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: active-accounts-list
  template:
    metadata:
      labels:
        app: active-accounts-list
    spec:
      containers:
        - name: slate-lists
          image: slate-lists:14f2c9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SLATE_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: active-accounts-list
                  key: SLATE_SERVER_ADDR
            - name: SLATE_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: active-accounts-list
                  key: SLATE_COLLECTION
          volumeMounts:
            - name: list-config
              mountPath: /etc/slate
              readOnly: true
      volumes:
        - name: list-config
          configMap:
            name: active-accounts-list
            items:
              - key: list.json
                path: list.json
---
apiVersion: v1
kind: Service
metadata:
  name: active-accounts-list
  namespace: acme
spec:
  selector:
    app: active-accounts-list
  ports:
    - port: 8080
      targetPort: 8080
