# GENERATED by gen.py — do not edit. 80 queries.
SELECT VALUE c.totalAmount FROM c
SELECT VALUE ABS(c.totalAmount) FROM c
SELECT VALUE FLOOR(c.totalAmount) FROM c
SELECT VALUE CEILING(c.totalAmount) FROM c
SELECT VALUE SQUARE(c.totalAmount) FROM c
SELECT VALUE SIGN(c.totalAmount) FROM c
SELECT VALUE c.totalAmount * 2 FROM c
SELECT VALUE c.totalAmount + 1 FROM c
SELECT VALUE c.totalAmount - 1 FROM c
SELECT VALUE c.id FROM c WHERE c.totalAmount > 1
SELECT VALUE c.id FROM c WHERE c.totalAmount >= 0
SELECT VALUE c.id FROM c WHERE c.totalAmount != 0
SELECT VALUE c.id FROM c ORDER BY c.totalAmount ASC
SELECT VALUE c.id FROM c ORDER BY c.totalAmount DESC OFFSET 1 LIMIT 2
SELECT VALUE c.status FROM c
SELECT VALUE UPPER(c.status) FROM c
SELECT VALUE LOWER(c.status) FROM c
SELECT VALUE REVERSE(c.status) FROM c
SELECT VALUE LENGTH(c.status) FROM c
SELECT VALUE c.id FROM c WHERE STARTSWITH(c.status, 'a')
SELECT VALUE c.id FROM c WHERE CONTAINS(c.status, 'e')
SELECT VALUE c.id FROM c WHERE c.status != 'zzz'
SELECT VALUE c.id FROM c ORDER BY c.status ASC
SELECT VALUE c.id FROM c ORDER BY c.status DESC OFFSET 1 LIMIT 2
SELECT VALUE totalAmount FROM c
SELECT VALUE d.totalAmount FROM c
SELECT VALUE c.totalAmount FROM c AS x
SELECT VALUE x.totalAmount FROM c AS x
SELECT VALUE p.totalAmount FROM coll p
SELECT VALUE c.nonexistent FROM c
SELECT VALUE c.a.b.c FROM c
SELECT c.id, (SELECT VALUE COUNT(1) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE COUNT(1) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE SUM(1) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE SUM(1) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE SUM(t.quantity) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE SUM(t.quantity) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE SUM(t.price) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE SUM(t.price) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE AVG(1) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE AVG(1) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE AVG(t.quantity) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE AVG(t.quantity) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE AVG(t.price) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE AVG(t.price) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE MIN(1) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE MIN(1) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE MIN(t.quantity) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE MIN(t.quantity) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE MIN(t.price) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE MIN(t.price) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE MAX(1) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE MAX(1) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE MAX(t.quantity) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE MAX(t.quantity) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, (SELECT VALUE MAX(t.price) FROM t IN c.items) AS v FROM c
SELECT c.id, (SELECT VALUE MAX(t.price) FROM t IN c.items WHERE t.quantity > 1) AS v FROM c
SELECT c.id, ARRAY(SELECT VALUE t.quantity FROM t IN c.items) AS a FROM c
SELECT c.id, ARRAY(SELECT VALUE t.quantity FROM t IN c.items WHERE t.quantity > 1) AS a FROM c
SELECT c.id, ARRAY(SELECT VALUE t.price FROM t IN c.items) AS a FROM c
SELECT c.id, ARRAY(SELECT VALUE t.price FROM t IN c.items WHERE t.quantity > 1) AS a FROM c
SELECT c.id, ARRAY(SELECT VALUE t.productName FROM t IN c.items) AS a FROM c
SELECT c.id, ARRAY(SELECT VALUE t.productName FROM t IN c.items WHERE t.quantity > 1) AS a FROM c
SELECT VALUE c.id FROM c WHERE EXISTS(SELECT VALUE t FROM t IN c.items WHERE t.quantity > 1)
SELECT VALUE c.id FROM c WHERE EXISTS(SELECT VALUE t FROM t IN c.items WHERE t.quantity >= 0)
SELECT VALUE c.id FROM c WHERE EXISTS(SELECT VALUE t FROM t IN c.items WHERE t.quantity != 0)
SELECT VALUE c.id FROM c WHERE (SELECT VALUE COUNT(1) FROM t IN c.items WHERE t.quantity > 1) >= 1
SELECT VALUE c.id FROM c WHERE (SELECT VALUE COUNT(1) FROM t IN c.items WHERE t.quantity >= 0) >= 1
SELECT VALUE c.id FROM c WHERE (SELECT VALUE COUNT(1) FROM t IN c.items WHERE t.quantity != 0) >= 1
SELECT VALUE c.id FROM c WHERE (SELECT VALUE COUNT(1) FROM t IN c.items) > 0
SELECT VALUE j FROM c JOIN j IN (SELECT VALUE t FROM t IN c.items WHERE t.quantity > 1)
SELECT c.id, j FROM c JOIN j IN (SELECT VALUE t FROM t IN c.items WHERE t.quantity > 1)
SELECT c.id, ARRAY_LENGTH(ARRAY(SELECT VALUE t.quantity FROM t IN c.items)) AS n FROM c
SELECT VALUE ARRAY_LENGTH(ARRAY(SELECT VALUE t FROM t IN c.items)) FROM c
SELECT c.id, (SELECT VALUE COUNT(1) FROM y IN (SELECT VALUE t.quantity FROM t IN c.items)) AS n FROM c
SELECT VALUE t FROM c JOIN t IN c.items
SELECT VALUE t FROM c JOIN t IN c.items WHERE t.quantity > 1
SELECT VALUE t.quantity FROM c JOIN t IN c.items
SELECT VALUE t.price FROM c JOIN t IN c.items
SELECT VALUE t.productName FROM c JOIN t IN c.items
